### ISSUE TITLE
Observing IO failure with error "java.lang.IllegalStateException..."

### ISSUE THREAD

**Issue by deenav** [pravega/pravega-operator#139] opened 2019-03-18 10:18 UTC
**While running moderate IO workload from pravega benchmark (Total - 10 readers, 10 writers, 1000 events/sec, 100 streams with 10 segments), Observing IO failure along with Bookkeeper & Segmentstore restarts after ~1 day.** 

Environment details: PKS / K8 with medium cluster:
```
3 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
5 worker nodes @ xlarge.cpu(8 cpu, 8 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```

Pravega details:
```
Pravega version: zk-closed-client-issue-0.5.0-2155.b68e912
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: adrianmo/pravega-operator:issue-134-5
```

```
NAMESPACE     NAME                                                 READY     STATUS      RESTARTS   AGE
default       pravega-benchmark                                    1/1       Running     0          1d
default       pravega-benchmark-1                                  1/1       Running     0          1d
default       pravega-benchmark-2                                  1/1       Running     0          1d
default       pravega-benchmark-3                                  1/1       Running     0          1d
default       pravega-benchmark-4                                  1/1       Running     0          1d
default       pravega-bookie-0                                     1/1       Running     0          1d
default       pravega-bookie-1                                     1/1       Running     0          1d
default       pravega-bookie-2                                     1/1       Running     1          1d
default       pravega-bookie-3                                     1/1       Running     1          1d
default       pravega-operator-775554574d-w65nx                    1/1       Running     0          1d
default       pravega-pravega-controller-8585485c7-mshnd           1/1       Running     0          1d
default       pravega-pravega-segmentstore-0                       1/1       Running     0          1d
default       pravega-pravega-segmentstore-1                       1/1       Running     1          1d
default       pravega-pravega-segmentstore-2                       1/1       Running     0          1d
default       pravega-zk-0                                         1/1       Running     0          1d
default       pravega-zk-1                                         1/1       Running     0          1d
default       pravega-zk-2                                         1/1       Running     0          1d
```

Client is showing below exception for most of the IO failed streams

```
java.lang.IllegalStateException: The requested reader: 0 cannot be added to the group because it is already in the group. Perhaps close() was not called?
        at io.pravega.client.stream.impl.ReaderGroupStateManager.initializeReader(ReaderGroupStateManager.java:114)
        at io.pravega.client.stream.impl.ClientFactoryImpl.createReader(ClientFactoryImpl.java:153)
        at io.pravega.client.stream.impl.ClientFactoryImpl.createReader(ClientFactoryImpl.java:139)
        at com.emc.pravega.perf.PravegaReaderWorker.<init>(PravegaReaderWorker.java:43)
        at com.emc.pravega.perf.PravegaPerfTest.lambda$main$0(PravegaPerfTest.java:128)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
        at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.emc.pravega.perf.PravegaPerfTest.main(PravegaPerfTest.java:131)
```

Segmentstore-1 log Error before restart:
```
2019-03-15 21:42:50,682 16551822 [BookKeeperClientScheduler-OrderedScheduler-0-0] INFO  o.a.b.proto.PerChannelBookieClient - Timed-out 21 operations to channel [id: 0x481f043c, L:/172.24.21.14:41596 - R:pravega-bookie-2.pravega-bookie-headless.default.svc.cluster.local/172.24.21.10:3181] for pravega-bookie-2.pravega-bookie-headless.default.svc.cluster.local:3181
```
Segmentstore-2 log Error:
```
2019-03-16 15:32:21,240 80703258 [core-4] ERROR i.p.s.s.h.handler.AppendProcessor - Error (Segment = 'Scope/test65/3.#epoch.0', Operation = 'append')
java.util.concurrent.CancellationException: OperationProcessor is shutting down.
        at io.pravega.segmentstore.server.logs.OperationProcessor.doStop(OperationProcessor.java:151)
        at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:280)
        at io.pravega.common.concurrent.Services.stopAsync(Services.java:61)
        at io.pravega.segmentstore.server.logs.DurableLog.doStop(DurableLog.java:246)
        at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:280)
        at io.pravega.common.concurrent.Services.stopAsync(Services.java:61)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainer.doStop(StreamSegmentContainer.java:281)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainer.doStop(StreamSegmentContainer.java:263)
        at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:280)
        at io.pravega.common.concurrent.Services.stopAsync(Services.java:61)
        at io.pravega.segmentstore.server.store.StreamSegmentContainerRegistry.stopContainer(StreamSegmentContainerRegistry.java:132)
        at io.pravega.segmentstore.server.host.ZKSegmentContainerMonitor.stopContainer(ZKSegmentContainerMonitor.java:207)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at io.pravega.segmentstore.server.host.ZKSegmentContainerMonitor.checkAssignment(ZKSegmentContainerMonitor.java:184)
        at org.apache.curator.framework.recipes.cache.NodeCache$4.apply(NodeCache.java:326)
        at org.apache.curator.framework.recipes.cache.NodeCache$4.apply(NodeCache.java:320)
        at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

[pravega-k8s-logging-2019-03-17-12-21-47-1.zip](https://github.com/pravega/pravega-operator/files/2977486/pravega-k8s-logging-2019-03-17-12-21-47-1.zip)

**Comment by deenav** [comment] 2019-03-18 10:33
Attaching STDOUT logs of `pravega-benchamrk` client for the streams 1 to 20 where only streams 8,12 & 13 `test8,test12 & test13` are running fine for last 2days and rest of them are failed with exceptions.

[pravega-benchmark-streams-1-20.zip](https://github.com/pravega/pravega-operator/files/2977558/pravega-benchmark-streams-1-20.zip)

**Comment by RaulGracia** [comment] 2019-03-18 11:48
In a first inspection of the logs, it looks like the problem is related to the fact that the benchmarking tool is not actually closing the reader and the problem happens when the test is executed the second time (`results1.out`):
1) We create the scope when we initiate the benchmark. This occurs in the constructor of `PravegaStreamHandler` that executes `streamManager.createScope(scope);`. At the beginning of the log file, we can see: 
```
[StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=-2521559382838744614] Tagging client request (createScope-Scope).
```
2) Then, the program seems to have been restarted, as we see the initial log lines repeated again at the end of the log:
```
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] INFO io.pravega.client.stream.impl.ControllerImpl - Controller client connecting to server at xxx:9090
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] INFO io.pravega.client.stream.impl.ControllerImpl - Controller client connecting to server at xxx:9090
[StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=699024922080637548] Tagging client request (createScope-Scope).
```
3) This means that we are creating again the readers in the ReaderGroup, but the program has not executed the `close()` for the readers. Therefore, it is correct that you see the error `The requested reader: 0 cannot be added to the group because it is already in the group. Perhaps close() was not called?`.

From these logs, I could imagine that the following is happening (please, confirm if this hypothesis is correct or not): 
- You are executing a resource-consuming (multiple threads) benchmark in a pod for which no resources have been requested, or they are not sufficient.
- Then, after some time of execution, the pod gets evicted by K8 due to lack of resources. This does not allow the application to close the readers properly.
- When the pod is restarted, it tries to create the Readers again but they have been already registered and not closed.

Does this make sense?

**Comment by deenav** [comment] 2019-03-18 12:36
Thanks @Raúl Gracia for your analysis.  One question arises is, if `pravega-benchmark` doesn't call `close()` for the readers then the same error message would have seen for all the 20 streams running from the same benchmark pod. Isn't it? Correct me if I'm wrong. 

As I mentioned already, `test6,test8 & test13` streams IO's are running fine from the same benchmark pod.

**Comment by shrids** [comment] 2019-05-29 10:43
@deenav PR: https://github.com/pravega/pravega-benchmark/pull/42 has the fix for issue https://github.com/pravega/pravega-benchmark/issues/37. As I understand this issue is due to benchmark tool not invoking reader#close() as described in issue 37 .

Could you verify with the latest bench mark once the PR is merged? We should close this issue based on verification outcome.

**Comment by RaulGracia** [comment] 2019-05-29 10:51
@shrids @deenav I have merged that PR, so you can verify if the issue persists (cc/ @kmgowda).

**Comment by pbelgundi** [comment] 2019-07-02 11:58
This is not an operator issue and the root cause on benchmark tool also has been fixed.
QA Verification issue for the same: https://github.com/pravega/pravega-benchmark/issues/49

**Closed by pbelgundi** 2019-07-02 11:58 UTC
Labels: kind/bug, priority/P2, status/needs-info, version 0.3.2
