### ISSUE TITLE
Helm Chart sets wrong Ledgers Path in Zookeeper

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega-operator#379] opened 2020-04-29 14:36 UTC
### Description
In GKE, I have tried to deploy Bookkeeper and Pravega via Helm charts and it does not work because of the following:
1) Deployed Bookkeeper Operator and Bookkeeper as follows:
```
helm install charts/bookkeeper-operator --name bookkeeper-operator
helm install charts/bookkeeper --name bookkeeper --set zookeeperUri=zookeeper-client:2181
```
Bookkeeper works fine and the metadata of ledgers is stored in Zookkeeper under this znode:
```
root@zookeeper-0:/apache-zookeeper-3.5.5-bin# bin/zkCli.sh ls /pravega/pravega/bookkeeper
...
WatchedEvent state:SyncConnected type:None path:null
[ledgers]
```
Then, I do the same to install Pravega Operator and Pravega:
```
helm install charts/pravega-operator --name pravega-operator
helm install charts/pravega --name pravega --set zookeeperUri=zookeeper-client:2181 --set bookkeeperUri="bookkeeper-pravega-bk-bookie-0.bookkeeper-pravega-bk-bookie-headless.default.svc.cluster.local:3181\,bookkeeper-pravega-bk-bookie-1.bookkeeper-pravega-bk-bookie-headless.default.svc.cluster.local:3181\,bookkeeper-pravega-bk-bookie-2.bookkeeper-pravega-bk-bookie-headless.default.svc.cluster.local:3181" --set pravega.longtermStorage=pravega-tier2
```
But the metadata for Pravega is pointing to a different Znode:
```
root@zookeeper-0:/apache-zookeeper-3.5.5-bin# bin/zkCli.sh ls /pravega/pravega-pravega
...
WatchedEvent state:SyncConnected type:None path:null
[buckets, cluster, garbagecollection, watermarks]
```

So, as you can see, the Pravega helm adds `pravega-` to the Zookeeper path, so it does not match with the Bookkeeper one. As we can see in the logs, this is where the Segment Store expects to find the Bookkeeper ledger metadata:
```
ledgersRootPath = /pravega/pravega-pravega/bookkeeper/ledgers
```
Since this is not the right path, the Segment Store keeps crashing all the time.

### Importance

Must have.

### Location

Helm chart.

### Suggestions for an improvement
We should consider 2 points here:
- Remove the `pravega-` added in the Pravega Znode path when Pravega is deployed.
- Enable `ledgersRootPath` to be set in the Helm chart parameters.

**Comment by SrishT** [comment] 2020-04-30 05:22
@RaulGracia the behavior u described here is the expected behavior. We are expected to provide the correct name of the pravega cluster (which in your case is `pravega-pravega` and not `pravega`) to the bookkeeper cluster in one of the following 2 ways :-
- within the values.yaml file if you are deploying it using charts.
https://github.com/pravega/bookkeeper-operator/blob/master/charts/bookkeeper/values.yaml#L10
- or within the config_map.yaml file if you are doing manual deployment. 
https://github.com/pravega/bookkeeper-operator/blob/master/deploy/config_map.yaml#L7

If this value is correctly set, the bookkeeper ledger metadata will be stored in the correct path where  the segmentstore expects to find it i.e. `/pravega/pravega-pravega/bookkeeper/ledgers`

**Comment by pbelgundi** [comment] 2020-04-30 05:45
@SrishT why is this marked as an enhancement?
Based on your comment above I would want to close this as "not an issue"

**Comment by SrishT** [comment] 2020-04-30 05:53
Since the description of this issue is expected behavior, I am closing this issue. @RaulGracia could you create a new issue which clearly explains what the issue is, what behavior is expected and why that change is necessary.

**Closed by SrishT** 2020-04-30 05:53 UTC
Labels: area/charts, priority/P2
