### ISSUE TITLE
`Controller api failed with error:` log observed on Pravega cluster when external access is enabled

### ISSUE THREAD

**Issue by deenav** [pravega/pravega-operator#94] opened 2018-11-20 19:48 UTC
**Problem description**
There are error messages as `Controller api failed with error:
java.util.concurrent.CompletionException: io.pravega.controller.store.stream.StoreException$IllegalStateException: Stream: _requeststream State: CREATING` while creating a stream on Pravega Controller when external access is enabled on the cluster. 

This error does not stop external IO operation on the Pravega cluster however it would be good to keep track of this error to investigate further on this.

Controller log Snip:
```
2018-11-20 10:42:47,146 835072 [controllerpool-77] WARN  i.p.c.f.ControllerClusterListener - java.lang.RuntimeException: sweeper not ready
2018-11-20 10:42:47,146 835072 [controllerpool-77] WARN  i.p.c.f.ControllerClusterListener - java.lang.RuntimeException: sweeper not ready
2018-11-20 10:42:47,813 835739 [grpc-default-executor-1] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - getCurrentSegments called for stream _system/_requeststream.
2018-11-20 10:42:47,816 835742 [controllerpool-76] ERROR i.p.c.s.r.g.v.ControllerServiceImpl - Controller api failed with error:
java.util.concurrent.CompletionException: io.pravega.controller.store.stream.StoreException$IllegalStateException: Stream: _requeststream State: CREATING
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983)
        at io.pravega.controller.store.stream.PersistentStreamBase.verifyLegalState(PersistentStreamBase.java:1399)
        at io.pravega.controller.store.stream.PersistentStreamBase.getActiveSegments(PersistentStreamBase.java:470)
        at io.pravega.controller.store.stream.AbstractStreamMetadataStore.lambda$getActiveSegments$13(AbstractStreamMetadataStore.java:370)
        at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.controller.store.stream.StoreException$IllegalStateException: Stream: _requeststream State: CREATING
        at io.pravega.controller.store.stream.StoreException.create(StoreException.java:99)
        at io.pravega.controller.store.stream.StoreException.create(StoreException.java:70)
        at io.pravega.controller.store.stream.PersistentStreamBase.lambda$verifyLegalState$182(PersistentStreamBase.java:1401)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        ... 15 common frames omitted
```

**Comment by Tristan1900** [comment] 2019-02-22 01:39
A similar error was found in Pravega repo [here](https://github.com/pravega/pravega/issues/2836).

But I cannot reproduce this error when I enable external access and run a `HelloWorld` sample on GKE. 

However, I do see this error happens sometimes at the beginning of creating a cluster with or without external access enabled, I kind of feel this is related to the performance of the underlying machines. 

From the log above we can see that controller is trying to get the active segment but found the stream is in `Creating` state, so I assume the stream is creating but just not fast enough. Eventually, it will become `Active` and error will be gone, which is consistent with your observation that the external IO operation is not blocked. 

WDYT? @adrianmo

**Comment by RaulGracia** [comment] 2019-02-22 07:41
This error is common and expected at the beginning of the execution of the Controller. When a Controller is instantiated, it also creates several "internal streams" (under `_system` scope) that are used to store events related to Controller tasks (e.g., scale stream). Until a new Controller creates those internal streams or notices that they already exist, it keeps waiting and showing this kind of errors. These messages are expected to disappear from a Controller log soon, but if they persist it may suggest that the Controller cannot create these streams, which is indeed an issue.

**Comment by adrianmo** [comment] 2019-02-22 10:33
@RaulGracia clarified the reason for these expected and harmless failures. I'm closing the issue. Please create a new issue if those failures persist and prevent clients from creating streams and using Pravega.

**Closed by adrianmo** 2019-02-22 10:33 UTC
Labels: kind/bug, priority/low, status/needs-investigation
