### ISSUE TITLE
pvc-tier2 can not connected after restart

### ISSUE THREAD

**Issue by safronovD** [pravega/pravega-operator#370] opened 2020-04-25 15:28 UTC
**Problem description**
When I restart my pravega_cluster (kubectl delete, kubectl apply), all pods start correctly, but it gives no response on curl GET.

![Screenshot_9](https://user-images.githubusercontent.com/40600792/80283439-3c624d80-8720-11ea-91bb-1f64c20635ad.png)

After I create new pvc pravega-tier2, all works.

Kubernetes state:
```
k8s@k8sp:~/k8s/pravega-operator$ kubectl get all | grep pravega
pod/example-pravega-controller-7c7475cbd4-9s8b8   1/1     Running   0          11m
pod/example-pravega-segmentstore-0                1/1     Running   0          11m
pod/example-pravega-segmentstore-1                1/1     Running   0          7m54s
pod/example-pravega-segmentstore-2                1/1     Running   0          7m40s
pod/pravega-operator-7b47777f6d-wbxtz             1/1     Running   0          27d
pod/pravega-writer-d5954f866-mrj6l                1/1     Running   0          6d21h
service/example-pravega-controller              ClusterIP   10.233.4.36     <none>        10080/TCP,9090/TCP                                                                                          11m
service/example-pravega-segmentstore-headless   ClusterIP   None            <none>        12345/TCP                                                                                                   11m
service/pravega                                 NodePort    10.233.27.115   <none>        10080:30952/TCP,9090:30768/TCP                                                                              7d3h
service/pravega-webhook-svc                     ClusterIP   10.233.29.51    <none>        443/TCP                                                                                                     27d
deployment.apps/example-pravega-controller   1/1     1            1           11m
deployment.apps/pravega-operator             1/1     1            1           27d
deployment.apps/pravega-writer               1/1     1            1           6d21h
replicaset.apps/example-pravega-controller-7c7475cbd4   1         1         1       11m
replicaset.apps/pravega-operator-7b47777f6d             1         1         1       27d
replicaset.apps/pravega-writer-d5954f866                1         1         1       6d21h
statefulset.apps/example-pravega-segmentstore   3/3     11m
```

Pravega version 0.5.0
$kubectl get pravegacluster -o yaml
[pravegacluster.yaml.txt](https://github.com/pravega/pravega/files/4533325/pravegacluster.yaml.txt)

$kubectl get pvc pravega-tier2 -o yaml
[nfs-pvc.yaml.txt](https://github.com/pravega/pravega/files/4533329/nfs-pvc.yaml.txt)

**Importance**
nice-to-have

**Problem location**
Pravega-controller spams one type of error. In attached log:
[pravega-controller.log](https://github.com/pravega/pravega/files/4533335/pravega-controller.log)

**Suggestions for an improvement**
Is it planned, that I see no error while deploying?

**Comment by pbelgundi** [comment] 2020-05-06 06:44
This issue occurs because tier2 stores state information and if on reinstall the old tier2 pvc is used, stale state gets used by Pravega.
There are 2 ways to solve this:
1. When re-installing Pravega operator should check if the LongTermStorage (tier2) is stale and already has some state information.
2. Pravega should not store state information in LongTermStorage (tier2)

**Comment by derekm** [comment] 2020-05-11 19:54
I asked @safronovD what expected behavior would be, and he replied:

> It would be better if pravega-operator checks tier-2 pvc at first. And then it gives any kind of error while creating of pravega-controller pod (how it works with no zk-cluster).

**Comment by Prabhaker24** [comment] 2020-06-22 04:23
After the pr https://github.com/pravega/pravega-operator/pull/405 pravega-operator won't mark the pravega deployment as ready in this case so we can close this issue.

**Comment by Prabhaker24** [comment] 2020-10-07 12:05
Closing this issue as we can't  check if the LongTermStorage (tier2) is stale and already has some state information from the pravega-operator once we are in the reconcile loop and readiness probe ensures that we don't mark the pravega-deployment as ready if controller can't create or assess the system scope.

**Closed by Prabhaker24** 2020-10-07 12:05 UTC
Labels: status/needs-investigation
