### ISSUE TITLE
Upgrade process fails to detect the error/failure and fails to set the `Error` status to `True`

### ISSUE THREAD

**Issue by deenav** [pravega/pravega-operator#186] opened 2019-05-17 13:15 UTC
**Upgrade process waits indefinitely for the failed pod to recover and not updating the `Error` and `upgrading` status appropriately**

When I tried to simulate upgrade failure scenario by upgrading Pravega cluster version from `0.5.0-2222.8ba543`1 to `0.5.0-2222` (Here 0.5.0-2222 docker image is not existing), upgrade process failing to detect the `ImagePullBackOff`  Error on the `Bookie-0` pod.

I was expecting the upgrade process will detect the failure/timeout and update the status of `Error` to `True` and `upgrading` status to `false`. But the upgrade process is waiting indefinitely (tested for more than a day) for `Bookie-0` pod to recover and not updating the status of upgrade failure.

**kubectl describe PravegaCluster output**
```
Status:
  Conditions:
    Last Transition Time:  2019-05-15T07:57:10Z
    Last Update Time:      2019-05-15T07:57:10Z
    Status:                True
    Type:                  Upgrading
    Last Transition Time:  2019-05-15T07:58:28Z
    Last Update Time:      2019-05-15T07:58:28Z
    Status:                False
    Type:                  PodsReady
    Status:                False
    Type:                  Error
  Current Replicas:        9
  Current Version:         0.5.0-2222.8ba5431
  Members:
    Ready:
      pravega-bookie-1
      pravega-bookie-2
      pravega-bookie-3
      pravega-pravega-controller-7f89bff94d-sct8n
      pravega-pravega-controller-7f89bff94d-wkdnk
      pravega-pravega-segmentstore-0
      pravega-pravega-segmentstore-1
      pravega-pravega-segmentstore-2
    Unready:
      pravega-bookie-0
  Ready Replicas:  8
  Replicas:        9
  Target Version:  0.5.0-2222
Events:            <none>
```
```
# kubectl get pravegacluster
NAME      VERSION              DESIRED VERSION   DESIRED MEMBERS   READY MEMBERS   AGE
pravega   0.5.0-2222.8ba5431                     9                 8               3d
```
**Pod status**
```
[root@master May-17]# kubectl get po  --all-namespaces
NAMESPACE     NAME                                                 READY   STATUS             RESTARTS   AGE
default       boiling-ragdoll-pravega-operator-7695d64cf-rvzdf     1/1     Running            0          4d
default       pravega-benchmark                                    1/1     Running            0          3d3h
default       pravega-bookie-0                                     0/1     ImagePullBackOff   0          2d5h
default       pravega-bookie-1                                     1/1     Running            0          3d1h
default       pravega-bookie-2                                     1/1     Running            0          3d1h
default       pravega-bookie-3                                     1/1     Running            0          3d1h
default       pravega-pravega-controller-7f89bff94d-sct8n          1/1     Running            0          3d1h
default       pravega-pravega-controller-7f89bff94d-wkdnk          1/1     Running            0          3d1h
default       pravega-pravega-segmentstore-0                       1/1     Running            0          3d1h
default       pravega-pravega-segmentstore-1                       1/1     Running            0          3d1h
default       pravega-pravega-segmentstore-2                       1/1     Running            0          3d1h
default       pravega-zk-0                                         1/1     Running            0          3d23h
default       pravega-zk-1                                         1/1     Running            0          3d23h
default       pravega-zk-2                                         1/1     Running            0          3d23h
default       shaka-zulu-nfs-client-provisioner-59d7f8f84c-tvh7w   1/1     Running            0          3d23h
default       zookeeper-operator-685bfcbbc5-7r48t                  1/1     Running            0          3d23h
```

**Logs from Pravega-operator:**
```
time="2019-05-15T07:57:10Z" level=info msg="syncing cluster version from 0.5.0-2222.8ba5431 to 0.5.0-2222"
ng statefulset (pravega-bookie) template image to 'devops-repo.isus.emc.com:8116/nautilus/bookkeeper:0.5.0-2222'"
time="2019-05-15T07:57:27Z" level=info msg="Reconciling PravegaCluster default/prtime="2019-05-15T07:57:10Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-15T07:57:10Z" level=info msg="updating statefulset (pravega-bookie) template image to 'devops-repo.isus.emc.com:8116/nautilus/bookkeeper:0.5.0-2222'"
time="2019-05-15T07:57:27Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-15T07:57:27Z" level=info msg="statefulset (pravega-bookie) status: 0 updated, 4 ready, 4 target"
time="2019-05-15T07:57:27Z" level=info msg="upgrading pod: pravega-bookie-0"
time="2019-05-15T07:57:57Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-15T07:57:58Z" level=info msg="statefulset (pravega-bookie) status: 0 updated, 4 ready, 4 target"
time="2019-05-15T07:57:58Z" level=info msg="upgrading pod: pravega-bookie-0"
time="2019-05-15T07:58:28Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-15T07:58:28Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-15T07:58:28Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-15T07:58:28Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-15T07:58:58Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-15T07:58:58Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-15T07:59:28Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-15T07:59:28Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-15T07:59:58Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
..............
...............
time="2019-05-17T12:47:59Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-17T12:47:59Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-17T12:48:29Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-17T12:48:29Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-17T12:48:59Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-17T12:48:59Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-17T12:49:29Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-17T12:49:30Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-17T12:50:00Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-17T12:50:00Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-17T12:50:30Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-17T12:50:30Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-17T12:51:00Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-17T12:51:00Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-17T12:51:30Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-17T12:51:30Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
 ```

**Comment by adrianmo** [comment] 2019-05-20 10:24
@deenav the recovery procedure for a failed upgrade is yet to be investigated and defined. The issue to keep track of it is #157. 

In the meantime, you can give it a try by doing the following:

1. Edit the `PravegaCluster` resources and revert the version back to `0.5.0-2222`.
2. Edit the `pravega-bookie` Statefulset and set the image tag to `0.5.0-2222`.
3. Delete the affected pod, i.e. `pravega-bookie-0`.

Let us know how it goes.

**Comment by deenav** [comment] 2019-05-20 10:59
@adrianmo I have tried the above steps but still `pravega-bookie-0` is referring to the old invalid image and fails to come up.

And actually this issue is filed for upgrade process should halt/exit if there is any failure/Error and set the `Error` status in `kubectl describe PravegaCluster` output to `true`.

**Comment by pbelgundi** [comment] 2019-08-22 12:10
Re-opening as this is currently only fixed for Bookkeeper. If we get similar error for Pravega Controller/Segment Store, upgrade still stalls.

**Comment by pbelgundi** [comment] 2019-08-26 06:25
Here are some reasons why a deployment could fail:
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#failed-deployment

We need to make sure when upgrade fails due to any of the above reasons, we're able to detect that in a reasonable amount of time and set cluster status to "Error", instead of entering a stalled state.

For `deployments`, one way of doing this is setting the property ".spec.progressDeadlineSeconds" to number of minutes we want to wait before declaring a Deployment as failed. With this set, we would need to check for the following deployment state to confirm a stalled deployment and based on this set UpgradeFailed status on Pravega Cluster:
```
Type=Progressing
Status=False
Reason=ProgressDeadlineExceeded
```

**Comment by pbelgundi** [comment] 2019-08-27 12:56
In case of statefulsets, k8s documentation states this:
```
Note that, even though the StatefulSet controller will not proceed to update the next Pod until its ordinal successor is Running and Ready, it will restore any Pod that fails during the update to its current version.
```
https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#updating-statefulsets

So if upgrade of segmentstore or bookies fails, operator would keep retrying and k8s would again roll the component back to old version. This can lead to an endless loop. We need to make sure this does not happen and we're able to fail the upgrade process if upgrading a pod to the next version is unsuccessful.

**Comment by pbelgundi** [comment] 2019-08-28 16:03
@Tristan1900 This is not directly related to rollback. 
Here we're working on figuring out what it takes to detect that Upgrade is stuck.
Once we are sure that Upgrade can't progress, we move the cluster status to "Error" condition ( Reason= "UpgradeFailed")
This state would be the trigger for a rollback.

**Comment by Tristan1900** [comment] 2019-08-29 06:39
@pbelgundi I see. I checked the doc and k8s code for statefulset, unlike deployment, there seems no way to know that if the update fails, also, there is no obvious way for a rolling update statefulset to roll back. Perhaps we could use also use `OnDelete` strategy for segmentstore, in this way we could know if there is an error happens just like updating the bookies. WDYT?

**Comment by pbelgundi** [comment] 2019-08-29 17:09
@Tristan1900 To sum up the problem, here are some reasons why our update ( or any rollout, including the very first install of pravega) could be stuck :
1. Incorrect configuration (wrong quota, permissions, limit ranges)
2. Network issues (ImagePullError)
3. K8s Cluster Issues.
4. Application issues (Application runtime misconfiguration or code bugs)
While we could explicitly check for some of these errors it would be impossible to check for all possible root causes and their combinations.

These causes could manifest as Pod staying in 'Pending' state or moving to 'Running' state but restarting frequently or failing Probes

My take on solving this is to `fail fast` wherever possible and at other times rely on a timeout ( at pod level / deployment or sts level) to detect that we're stuck.

**Comment by pbelgundi** [comment] 2019-08-29 17:34
Here are some ways in which we can detect and take action on a stuck upgrade:
1. We explicitly check for 'ImagePullErrors' and fail upgrade if these occur. (Srishti has added this for Bookkeeper see PR#253) 
Same needs to be done for Controller and Segment Store) 
Add below code at these lines:
https://github.com/pravega/pravega-operator/blob/master/pkg/controller/pravegacluster/upgrade.go#L225
https://github.com/pravega/pravega-operator/blob/master/pkg/controller/pravegacluster/upgrade.go#L181
```
	_, err := r.checkUpdatedPods(sts, p.Status.TargetVersion)
		if err != nil {
			// Abort if there is any errors with the updated pods
			return false, err
		}
		// Upgrade still in progress
		return false, nil
```
2. When Controller upgrade is in progress,  check if the deployment enters the 'ProgressDeadlineExceeded' condition and if it does fail the upgrade.
3. In Controller DeploymentSpec set `minReadySeconds` to a reasonable value for controller, and when checking for deployment completion during upgrade,
 instead of this check:
```
	// Check whether the upgrade is in progress or has completed
	if deploy.Status.UpdatedReplicas != deploy.Status.Replicas ||
		deploy.Status.UpdatedReplicas != deploy.Status.ReadyReplicas
```
we do
```
// Check whether the upgrade is in progress or has completed
	if deploy.Status.UpdatedReplicas != deploy.Status.Replicas ||
	deploy.Status.UnavailableReplicas > 0 {
	// deployment has not completed yet
	// here check for ImagePullError
	// check if replica creation has failed - deploy.Status.DeploymentCondition[] contains `DeploymentReplicaFailure with Status=true`
	return false, nil
}
```

**Comment by pbelgundi** [comment] 2019-08-29 17:38
Regarding Statefulsets I agree that they don't really provide any easy mechanisms for detecting a stuck rollout. 
Other than checking for ImagePullErrors, here are some ways I could think of for detecting a stuck deployment:
a. Use onDelete updateStrategy.
b. When we delete a pod in the sts (for upgrade), we add a new condition to the stateful set.....
Something on these lines...
```
StatefulSetConditionType := "UpdatingPods"
Status := true
LastTransitionTime := now
Reason := "Updating pod example-0"
```	
c. After this, everytime we enter the reconcile loop , 
we check current time against `LastTransitionTime` of above condition and if this difference is greater than a certain threshold ( say 10 mins) we fail the upgrade.
d. When we take-up a new pod for updation, we reset `LastTransitionTime ` in above condition and change Reason to `Updating pod example-1`

Let me know of you can think of more/better ways to detect issues with statefulset rollouts....

**Comment by Tristan1900** [comment] 2019-08-29 20:34
@pbelgundi Thanks! It looks good to me. Will try to have a PR today for review.

**Closed** 2019-09-13 06:59 UTC
Labels: area/controller, area/upgrade, kind/bug, priority/P1, version 0.4.0
