### ISSUE TITLE
Manual recovery of Cluster is not possible if Rollback is failed

### ISSUE THREAD

**Issue by Richa-Srivastava** [pravega/pravega-operator#284] opened 2019-10-12 06:47 UTC
Steps done are as follows:
1. Tried failing upgrade by providing incorrect Version(0.6.0.2391.97363b3) inside `Kubectl edit PravegaCluster` version field. This made Upgrade to fail.
2. Triggered rollback process by providing previous correct version(0.6.0-2391.97363b3). 
3. When the rollback was in progress, I edited PravegaCluster version again to some incorrect version(0.6.0-239197363b3) and this caused  rollback to failed.
4. Tried recovering cluster manually by providing correct pravega version: 0.6.0-2391.97363b3 but this didn't trigger  upgrade process and the cluster's config became like:
```
root@osboxes:/home/osboxes# k get po
NAME                                                 READY   STATUS             RESTARTS   AGE
grafana-5c4689f447-264jd                             1/1     Running            0          8d
influxdb-84bcfc9789-xfnqp                            1/1     Running            0          8d
pravega-benchmark-5                                  1/1     Running            0          18d
pravega-bookie-0                                     1/1     Running            0          28m
pravega-bookie-1                                     0/1     ImagePullBackOff   0          49m
pravega-bookie-2                                     1/1     Running            0          18h
pravega-bookie-3                                     1/1     Running            0          18h
pravega-operator-5f45c98857-kdd2x                    1/1     Running            0          18h
pravega-pravega-controller-9dbc95bb-dmjmt            1/1     Running            0          18h
pravega-pravega-controller-9dbc95bb-k6pfq            1/1     Running            0          18h
pravega-pravega-segmentstore-0                       1/1     Running            0          18h
pravega-pravega-segmentstore-1                       1/1     Running            0          18h
pravega-pravega-segmentstore-2                       1/1     Running            0          18h
pravega-zk-0                                         1/1     Running            0          18h
pravega-zk-1                                         1/1     Running            0          18h
pravega-zk-2                                         1/1     Running            0          18h
pravega-zk-3                                         1/1     Running            0          18h
pravega-zk-4                                         1/1     Running            0          18h
shaka-zulu-nfs-client-provisioner-755996548f-crw46   1/1     Running            0          18h
zookeeper-operator-b7c699ffb-49bbw                   1/1     Running            0          18h
```
PravegaCluster `Status` is shown as:
```
Status:
  Conditions:
    Last Transition Time:  2019-10-12T05:22:04Z
    Last Update Time:      2019-10-12T05:22:04Z
    Status:                False
    Type:                  Upgrading
    Last Transition Time:  2019-10-12T05:10:58Z
    Last Update Time:      2019-10-12T05:10:58Z
    Status:                False
    Type:                  PodsReady
    Last Transition Time:  2019-10-12T05:22:04Z
    Last Update Time:      2019-10-12T05:44:29Z
    Message:               failed to sync bookkeeper version. updating statefulset (pravega-bookie) failed due to progress deadline exceeded
    Reason:                RollbackFailed
    Status:                True
    Type:                  Error
    Last Transition Time:  2019-10-12T05:44:29Z
    Last Update Time:      2019-10-12T05:44:29Z
    Status:                False
    Type:                  RollbackInProgress
  Current Replicas:        9
  Current Version:         0.6.0-2391.97363b3
  Members:
    Ready:
      pravega-bookie-0
      pravega-bookie-2
      pravega-bookie-3
      pravega-pravega-controller-9dbc95bb-dmjmt
      pravega-pravega-controller-9dbc95bb-k6pfq
      pravega-pravega-segmentstore-0
      pravega-pravega-segmentstore-1
      pravega-pravega-segmentstore-2
    Unready:
      pravega-bookie-1
  Ready Replicas:  8
  Replicas:        9
  Version History:
    0.6.0-2391.97363b3
```
And its config as:
```
root@osboxes:/home/osboxes# kubectl get po -o jsonpath={...image}|tr -s [[:space:]] "\n"|sort|uniqdevops-repo.isus.emc.com:8116/nautilus/bookkeeper:0.6.0-2391.97363b3
bookkeeper:0.6.0.2391.97363b3
pravega:0.6.0-2391.97363b3
openjdk:8
pravega/pravega-operator:0.4.2-rc2
pravega/zookeeper:0.2.4
pravega/zookeeper-operator:0.2.4
quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11
pravega-grafana:latest
pravega-influxdb:latest
```
Now both `Upgrading` and `Rollback` status is false and cluster is in `unhealthy` state:
```
 Status:                False
    Type:                  Upgrading
    Last Transition Time:  2019-10-12T05:10:58Z
    Last Update Time:      2019-10-12T05:10:58Z
    Status:                False
    Type:                  PodsReady
    Last Transition Time:  2019-10-12T05:22:04Z
    Last Update Time:      2019-10-12T05:44:29Z
    Message:               failed to sync bookkeeper version. updating statefulset (pravega-bookie) failed due to progress deadline exceeded
    Reason:                RollbackFailed
    Status:                True
    Type:                  Error
    Last Transition Time:  2019-10-12T05:44:29Z
    Last Update Time:      2019-10-12T05:44:29Z
    Status:                False
    Type:                  RollbackInProgress
```
Attaching log in Jira.

**Comment by pbelgundi** [comment] 2019-10-16 04:18
@Richa-Srivastava  Manual recovery after Rollback Failure is supported and it does work properly.

Editing of cluster version during Rollback (when Rollback is InProgress), is not expected and 

this issue occurs because version was updated again when rollback was in Progress.

Please provide appropriate title to the issue.

**Comment by SrishT** [comment] 2019-10-23 11:21
Closing this as it is a duplicate of #283

**Closed by SrishT** 2019-10-23 11:21 UTC
Labels: priority/P2
