### ISSUE TITLE
Java 11 JVM Options Compatibility

### ISSUE THREAD

**Issue by co-jo** [pravega/pravega-operator#451] opened 2020-09-22 00:58 UTC
### Description

Once Pravega is built using Java 11, the current JVM defaults will no longer be valid. `+UseCGroupMemoryLimitForHeap` is no longer recognized, and should be succeeded by `+UseContainerSupport. ` 
### Importance

Must-have

### Location

* `doc/pravega-options.md`
* `pkg/controller/pravega/pravega_controller.go`
* `pkg/controller/pravega/pravega_segmentstore.go`

### Suggestions for an improvement

Replace `+UseCGroupMemoryLimitForHeap`  with `+UseContainerSupport. `.

**Comment by SrishT** [comment] 2020-09-22 06:08
This issue looks like a duplicate of https://github.com/pravega/pravega-operator/issues/300

**Closed** 2020-09-22 06:10 UTC
