### ISSUE TITLE
Failed to mount the volume after node restart in PKS

### ISSUE THREAD

**Issue by Richa-Srivastava** [pravega/pravega-operator#170] opened 2019-04-29 12:03 UTC
After node failure, the pods corresponding to that node became in unknown status and it took more than 1 hour for new node to come up and once the node became in `Ready` Status, all other pods became in `Running` status except bookkeeper:
```
root@osboxes:/usr/local/go/bin/src/github.com# kubectl get po --all-namespaces
NAMESPACE           NAME                                                 READY     STATUS              RESTARTS   AGE
default             pravega-bookie-0                                     1/1       Running             0          5h
default             pravega-bookie-1                                     0/1       ContainerCreating   0          43m
default             pravega-bookie-2                                     1/1       Running             0          5h
default             pravega-operator-779879b48-z9hck                     1/1       Running             0          5h
default             pravega-pravega-controller-84948d8895-j2vhz          1/1       Running             0          5h
default             pravega-pravega-controller-84948d8895-ttvsl          1/1       Running             0          5h
default             pravega-pravega-segmentstore-0                       1/1       Running             0          5h
default             pravega-pravega-segmentstore-1                       1/1       Running             0          4h
default             pravega-pravega-segmentstore-2                       1/1       Running             0          4h
default             pravega-zk-0                                         1/1       Running             0          5h
default             pravega-zk-1                                         1/1       Running             0          43m
default             pravega-zk-2                                         1/1       Running             0          5h
default             pravega-zk-3                                         1/1       Running             0          5h
default             shaka-zulu-nfs-client-provisioner-59d7f8f84c-ckkmx   1/1       Running             0          5h
default             zookeeper-operator-685bfcbbc5-4k8t8                  1/1       Running             0          2h
kube-system         heapster-85647cf566-nnhzz                            1/1       Running             0          2h
kube-system         kube-dns-7559c96fc4-kq5n9                            3/3       Running             0          13d
kube-system         kubernetes-dashboard-5f4b59b97f-hrwmz                1/1       Running             1          9d
kube-system         metrics-server-555d98886f-cp9k6                      1/1       Running             0          13d
kube-system         monitoring-influxdb-cdcf4674-cgxzp                   1/1       Running             0          13d
kube-system         tiller-deploy-95d654d46-dfqh8                        1/1       Running             0          5h
pks-system          cert-generator-v0.11-6hg96                           0/1       Completed           0          13d
pks-system          event-controller-56f9597df8-hq2nq                    2/2       Running             1          13d
pks-system          fluent-bit-6l4hv                                     2/2       Running             0          13d
pks-system          fluent-bit-7nqfx                                     2/2       Running             0          39m
pks-system          fluent-bit-svnb2                                     2/2       Running             0          9d
pks-system          fluent-bit-tdxnj                                     2/2       Running             0          13d
pks-system          fluent-bit-vml52                                     2/2       Running             0          13d
pks-system          sink-controller-65595c498b-dwrhc                     1/1       Running             0          2h
pks-system          telemetry-agent-559f9c8855-55fb8                     1/1       Running             0          23h
pravega-longevity   small-key-manager-7d54fbf9f7-tw7zn                   1/1       Running             0          2h
pravega-longevity   small-key-worker-57b474f5cb-sd4l9                    1/1       Running             0          2h
```
Following are the describe log for the BookKeeper which shows that it is failing to mount PVCs of journals, Ledgers and Indexes:
```
Events:
  Type     Reason                  Age                From                                           Message
  ----     ------                  ----               ----                                           -------
  Normal   Scheduled               38m                default-scheduler                              Successfully assigned default/pravega-bookie-1 to d71da967-5c65-48e1-b659-6f709879af5f
  Warning  FailedAttachVolume      38m                attachdetach-controller                        Multi-Attach error for volume "pvc-6315e9a5-6a4a-11e9-bb63-005056bac429" Volume is already exclusively attached to one node and can't be attached to another
  Warning  FailedAttachVolume      38m                attachdetach-controller                        Multi-Attach error for volume "pvc-63185495-6a4a-11e9-bb63-005056bac429" Volume is already exclusively attached to one node and can't be attached to another
  Warning  FailedAttachVolume      38m                attachdetach-controller                        Multi-Attach error for volume "pvc-631b0124-6a4a-11e9-bb63-005056bac429" Volume is already exclusively attached to one node and can't be attached to another
  Warning  FailedMount             34m (x2 over 36m)  kubelet, d71da967-5c65-48e1-b659-6f709879af5f  Unable to mount volumes for pod "pravega-bookie-1_default(6fc67ee0-6a6e-11e9-bb63-005056bac429)": timeout expired waiting for volumes to attach or mount for pod "default"/"pravega-bookie-1". list of unmounted volumes=[journal ledger index]. list of unattached volumes=[journal ledger index default-token-khgpq]
  Normal   SuccessfulAttachVolume  32m                attachdetach-controller                        AttachVolume.Attach succeeded for volume "pvc-6315e9a5-6a4a-11e9-bb63-005056bac429"
  Normal   SuccessfulAttachVolume  32m                attachdetach-controller                        AttachVolume.Attach succeeded for volume "pvc-63185495-6a4a-11e9-bb63-005056bac429"
  Normal   SuccessfulAttachVolume  32m                attachdetach-controller                        AttachVolume.Attach succeeded for volume "pvc-631b0124-6a4a-11e9-bb63-005056bac429"
  Warning  FailedMount             32m                kubelet, d71da967-5c65-48e1-b659-6f709879af5f  MountVolume.MountDevice failed for volume "pvc-6315e9a5-6a4a-11e9-bb63-005056bac429" : failed to mount the volume as "ext4", it already contains unknown data, probably partitions. Mount error: mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/plugins/kubernetes.io/vsphere-volume/mounts/[vsanDatastore] 00c73e5c-aa18-9890-ac73-246e966ddcf0/kubernetes-dynamic-pvc-6315e9a5-6a4a-11e9-bb63-005056bac429.vmdk --scope -- mount -t ext4 -o defaults /dev/disk/by-id/wwn-0x6000c2906aeb2fd5358ce099896c689d /var/lib/kubelet/plugins/kubernetes.io/vsphere-volume/mounts/[vsanDatastore] 00c73e5c-aa18-9890-ac73-246e966ddcf0/kubernetes-dynamic-pvc-6315e9a5-6a4a-11e9-bb63-005056bac429.vmdk
Output: Running scope as unit run-re3e28fe6d5a64ca1bf9282786f810ed3.scope.
mount: wrong fs type, bad option, bad superblock on /dev/sdf,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
```
Attaching the describe logs for the corresponding bookkeeper
[Describe_logs_Bookie_ContainerCreating.log](https://github.com/pravega/pravega-operator/files/3127243/Describe_logs_Bookie_ContainerCreating.log)

**Comment by Tristan1900** [comment] 2019-05-10 06:16
@Richa-Srivastava Thanks for the report of this issue!
I am having some difficulties reproducing this error. Could you please tell me how did you bring down the node and make it comes up again in PKS? Thanks a lot!

**Comment by Richa-Srivastava** [comment] 2019-05-10 10:45
@Tristan1900 , One node for pks cluster went down on its own and became `Not Ready` .Once the node recovered (almost after 1 hour), the bookkeeper which was residing on that node became in `ContainerCreating` Status and it never became running after that. This full operation happened on its own and that time I observed this behavior and hence reported.
Issue: https://github.com/pravega/pravega-operator/issues/171 was also observed and raised during this operation.

**Comment by EronWright** [comment] 2019-05-10 21:53
Looks to me that the vsan disk is corrupt or otherwise unusable.   The recovery step would assumedly be for the human admin to delete the pod, which should cause the statefulset to construct a new `pravega-bookie-3` (i.e. a new bookie similar to a scale event).

**Comment by Tristan1900** [comment] 2019-05-16 00:24
Thanks @EronWright for the input! I have tried to do that but unluckily it didn't work.
After investigation, here is what I have found for now.
1. These logs are expected 
```
  Warning  FailedAttachVolume      38m                attachdetach-controller                        Multi-Attach error for volume "pvc-6315e9a5-6a4a-11e9-bb63-005056bac429" Volume is already exclusively attached to one node and can't be attached to another
  Warning  FailedAttachVolume      38m                attachdetach-controller                        Multi-Attach error for volume "pvc-63185495-6a4a-11e9-bb63-005056bac429" Volume is already exclusively attached to one node and can't be attached to another
  Warning  FailedAttachVolume      38m                attachdetach-controller                        Multi-Attach error for volume "pvc-631b0124-6a4a-11e9-bb63-005056bac429" Volume is already exclusively attached to one node and can't be attached to another
  Warning  FailedMount             34m (x2 over 36m)  kubelet, d71da967-5c65-48e1-b659-6f709879af5f  Unable to mount volumes for pod "pravega-bookie-1_default(6fc67ee0-6a6e-11e9-bb63-005056bac429)": timeout expired waiting for volumes to attach or mount for pod "default"/"pravega-bookie-1". list of unmounted volumes=[journal ledger index]. list of unattached volumes=[journal ledger index default-token-khgpq]
  Normal   SuccessfulAttachVolume  32m                attachdetach-controller                        AttachVolume.Attach succeeded for volume "pvc-6315e9a5-6a4a-11e9-bb63-005056bac429"
  Normal   SuccessfulAttachVolume  32m                attachdetach-controller                        AttachVolume.Attach succeeded for volume "pvc-63185495-6a4a-11e9-bb63-005056bac429"
  Normal   SuccessfulAttachVolume  32m                attachdetach-controller                        AttachVolume.Attach succeeded for volume "pvc-631b0124-6a4a-11e9-bb63-005056bac429"
```
What happens is when a statefulset pod is moved to another node, k8s will wait for 6 minutes before attaching the pv to the new node. This is a known [issue](https://github.com/kubernetes/kubernetes/issues/53059), but it eventually it will attach the pv and everything will work.

2. The problem is actually reflected by this line of the log.
```
failed to mount the volume as "ext4", it already contains unknown data, probably partitions. Mount error: mount failed: exit status 32
```
I'm not sure what causes the node failure in the issue, but I can reproduce it by logging into one of the VM in PKS cluster and do `sudo reboot`. After reboot, the VM node will be stuck at `starting` status forever if we run `bosh vms -d <deployment name>` and `node status` will also be stuck at `NotReady`. However, we can ssh into that VM and found everything is running. Strange...
Run `cat /proc/partitions` in that VM before and after reboot, one of the BK volumes is partitioned, for example, `journal-0` is mounted as `sda` before but it becomes `sda1, sda2` after the reboot. This is the reason that causes the error as the log says ` probably partitions` because with partition we have to mount it separately. I have no idea why this partitioning happens. : (

3. I have done the same experiment in GKE environment. When I ssh into one of the instances and do reboot, the instance quickly reboots without error and node status becomes `Ready`. Also, statefulset pods can be migrated to another node successfully. 

I feel that there is a bug in PKS that causes this issue but it is hard to identify, any suggestions?

**Comment by adrianmo** [comment] 2019-05-30 10:27
@Tristan1900 yes, this looks like a PKS environment issue, can you please report this issue to the PKS folks and add a reference to this thread? Thank you.

**Comment by sumit-bm** [comment] 2019-07-03 12:37
I think we need more discussion around it, @adrianmo  mentioned liveness check and POD recovery with Pravega perspective needs to be changed so that it would recover these situations. What is the PKS environment issue here?

**Comment by ravisharda** [comment] 2019-07-03 13:01
@sumit-bm please see the comments above that describe the analysis of the issue. 

Could someone create a PKS issue and check with PKS about why the issue might have occurred upon VM restart? @Tristan1900 has described in detail about one of the scenarios where he could reproduce the issue in PKS (which he did not see in GKE). 

This doesn't look like a Pravega bug. I'm changing the labels accordingly.

**Comment by pbelgundi** [comment] 2019-07-03 13:32
> I think we need more discussion around it, @adrianmo mentioned liveness check and POD recovery with Pravega perspective needs to be changed so that it would recover these situations. What is the PKS environment issue here?

I don't see how liveness probe can help here. 

Clearly the node has failed to come up because of failure to mount pvc volume :
```
Warning  FailedMount  32m  kubelet, d71da967-5c65-48e1-b659-6f709879af5f  MountVolume.MountDevice failed for volume "pvc-6315e9a5-6a4a-11e9-bb63-005056bac429" : failed to mount the volume as "ext4", it already contains unknown data, probably partitions. Mount error: mount failed: exit status 32
```
Is this a consistently reproducible issue on PKS? Or a one-off case?

As @Tristan1900 mentioned earlier,  a similar node restart was attempted on GKE and no such issue was noticed  and the bk sts came up successfully without any issues. This leads us to believe that this is a PKS problem.

**Comment by Tristan1900** [comment] 2019-07-03 16:43
@sumit-bm This is an environmental issue, the PKS is behaving weird and it cannot mount the PVC back. I just create a GKE cluster 10 minutes ago and run the same experiment again, all pods come back up successfully and quickly after I manually `sudo reboot` a GKE node.
```
NAME                                               READY   STATUS    RESTARTS   AGE
loitering-gibbon-nfs-server-provisioner-0          1/1     Running   1          66m
pravega-operator-7c779b6c4f-txm54                  1/1     Running   0          9m14s
pravega-test-bookie-0                              1/1     Running   1          8m44s
pravega-test-bookie-1                              1/1     Running   0          8m44s
pravega-test-bookie-2                              1/1     Running   0          8m43s
pravega-test-pravega-controller-7dbcb68c9c-7q7fh   1/1     Running   0          8m44s
pravega-test-pravega-segmentstore-0                1/1     Running   0          8m43s
zk-0                                               1/1     Running   0          34m
zk-1                                               1/1     Running   1          34m
zk-2                                               1/1     Running   1          33m
zookeeper-operator-77f486d6b7-xv56l                1/1     Running   1          66m

```

**Comment by sumit-bm** [comment] 2019-07-03 18:21
@pbelgundi @ravisharda @fpj, we need to look into these cases more seriously. As far my understanding, in GKE cluster a node failure is not possible to perform, as those are in GKE control and not exposed to end user. In PKS environment, failing a node and recovery is not similar in GKE node restart. You can definitely check with PKS support but if customer get into these issues means it is huge outages (1 and 1/2 hour).

**Comment by Tristan1900** [comment] 2019-07-03 21:15
@sumit-bm Sorry I didn't run with any IO, it's just a plain cluster because the original problem does not mention any IO. The pod comes back up in only a few seconds. 

From what I see it is a problem that in PKS when the node comes back up, the BK is not able to recover itself. But from my experiment in GKE the BK can recover itself, so I think it is a PKS problem. When you said the GKE restarted node is not the same as PKS failing node + recovery scenario, could you please share more information of what is the difference between these two? 

I think theoretically, the user should not experience any outages when the node goes down because there should be redundancy(more than 3 Bookies) in BK cluster and everything should work just fine. What do you think? Thanks

**Comment by sachin-j-joshi** [comment] 2019-09-26 17:27
We need to narrow down this problem and possibly split into three sub problems.

1.  **Failure to mount NFS** . When nfs client provisioning pod is deleted then until it is successfully running again any new pod creation will continue to fail because the PVC can not be satisfied and volume can not be mounted inside pods. However once nfs client provisioner is back the pod should simply work. Segment store is the only component that depends on nfs. 

- @ManishKumarKeshri narrowed down this scenario and by only deleting nfs provsioner and SS pods was able to verify that Pravega does recover properly.

2. **Failure to mount standard volume** - This is a cluster "local" tier-1 volume. Any failure to mount should result in pod not starting. There is nothing inside the pod that can help here. If mount is not present the pod **should** fail immediately. The only possible pravega bug is when that does not happen. (ie. the pod does not fail).

- if the tier-1 volume is eventually mounted then expectation is pravega components should recover. Question is once volume *is* able to be mounted , do Pravega components resume normally. If not it why not?

3. If the underlying tier-1 volume is lost (or corrupted) . How should Pravega operator handle it. (Or rather can it handle it and even importantly should it handle it?

**Comment by Prabhaker24** [comment] 2020-11-06 10:13
Closing this issue as this is specific to pks environment.

**Closed by Prabhaker24** 2020-11-06 10:13 UTC
Labels: area/environment, status/needs-investigation
